spring.application.name=trucking
spring.application.version=1.0.0-SNAPSHOT
spring.application.group=mz.co.nextgenit.trucking

spring.datasource.url=jdbc:mysql://localhost:3306/trucking?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

